language: php

php:
  - 7.1
  - 7.2

install:
  - composer update
  - composer require php-coveralls/php-coveralls --dev

script: vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
